### PR TITLE
Sway - the way you vote

### PR DESCRIPTION
**Pull request by codebam**

### CODE REVIEW

**Comment by codebam** [comment]
https://etherscan.io/tx/0x5ed3b4b60d9baf4872842e71e329e11ce7af9d984ec48d854093498fea6783ac

**Comment by codebam** [comment]
I didn't have enough Ether to publish this the second time so I used less gas. It's still deploying and this commit will need to be updated

**Comment by codebam** [comment]
You guys have to update your CI. Let me do that for you

**Comment by codebam** [comment]
Updated with the correct contract address

**Comment by codebam** [comment]
Credits to Micah in Discord for the idea

**Comment by codebam** [comment]
Verifying the source code on Etherscan now

**Comment by codebam** [comment]
Redeployed as I forgot the last constructor parameter... cost me $40 rip

**Comment by codebam** [comment]
I can't get it to verify. can someone help me?

constructor arguments were:

address: 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
address: 0x5e4be8Bc9637f0EAA1A755019e06A68ce081D58F
UInt: 10000000000

**Comment by Hiturunk** [comment]
Just want to say Penguin Party has nothing to do with this Merge Request.

**Comment by codebam** [comment]
Verified https://etherscan.io/verifyContract-solc?a=0x8D8F8DDf4c190c116C470F08051bd5079e7D1F14&c=v0.6.12%2bcommit.27d51765&lictype=5

**Comment by codebam** [comment]
I'd appreciate if you guys could take a look. I might have made mistakes but I think it works? All it does is vote no anyways

**Comment by codebam** [comment]
https://www.seanbehan.dev/2020/sway/

Also available on IPFS at /ipns/www.seanbehan.dev/2020/sway/

This isn't finalized, there's more I want to say

**Comment by NoahZinsmeister** [comment]
thanks for the effort @codebam , but since this repo is meant to document already deployed code, we won't be making changes to it going forward

**Comment by codebam** [comment]
That's okay. I will keep using my fork. Thanks!

**Pull request closed without merging**
